# Generated by Django 4.1.7 on 2023-03-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_create_by_game_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="created_by",
        ),
    ]
